name: check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install --omit=dev
      - run: npm run check
      - run: ENV_LOGGER_CONFIG=config/site.example.json npm run config-check
